### ISSUE TITLE
Travis CI, is working?

### ISSUE THREAD

**Issue by tamerNasser** [facn6/Week5-sam-ameer-make-notes#26]
Are you sure thats how you should configure travis?
Take a look here, [Ghassan & Ayah project](https://github.com/facn6/AYGH/blob/master/.travis.yml)  :green_heart:

https://github.com/facn6/Week5-sam-ameer-make-notes/blob/402e59328f72471b207d9d50bd0755cb6bc2f5c5/.travis.yml#L1-L7

**Comment by samjam48** [comment]
Yes it's working and using api keys and a bunch of other wierd google setting stuff that is an arse to make run.

But the link was useful and updating

**Comment by tamerNasser** [comment]
It looks like you fixed it now.
