### ISSUE TITLE
API key 🔑 

### ISSUE THREAD

**Issue by g4ss4n** [facn6/Week5-sam-ameer-make-notes#30]
Spent more than 10 min to find how to get a key!
it would help if you explained it in an easier way or provide us with step by step tutorial!

**Comment by samjam48** [comment]
Really sorry. I was being super fast just so you had a readme to use.
The google api is ultimately very long. What I should have said.

If you want to use this project to help with your own google api project then it will help you and is worth creating an api key for. If you do not already have a google console account for using their API's it will take a long time which is excessive for trying to quickly review code 😬

I owe you a beer / falafel / cookie 🤗
