### ISSUE TITLE
deploy to heroku

### ISSUE THREAD

**Issue by ameerkas** [facn6/Week5-sam-ameer-make-notes#6]
- [x] - host project on heroku
- [x] - add api keys to heroku env variables
- [x] - ammend code to run on heroku
- [x] - Add google-config.json to env variables (and check it works!)

**Comment by samjam48** [comment]
hosted but needs settings edited in code to actually run...

**Comment by tamerNasser** [comment]
Don't forget to change the start script in your package.json, you should use 'node' instead of 'nodemon' as nodemon is installed globally in your own machine and not on Heroku's env.

**Comment by samjam48** [comment]
yes that what the task  "- ammend code to run on heroku" is for.

**Comment by samjam48** [comment]
6
